"use client"

import { useRouter } from "next/navigation"
import { ArrowUpLeft, History, Mail, NotebookPen, PenLine, RefreshCw } from "lucide-react"
import { toast } from "sonner"
import { CopyButton } from "@/components/common/copy-button"
import { EmptyState } from "@/components/common/empty-state"
import { Notice } from "@/components/common/notice"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { saveNote } from "@/lib/storage/notes"
import { cn } from "@/lib/utils"
import { FORMATS, MAILTO_BODY_LIMIT, modeLabel, type WriterFormat, type WriterLength, type WriterMode, type WriterTone } from "./writer-options"

/** Exactly what is sent (as JSON) to the `write` assist job. */
export interface WriteRequest {
  mode: WriterMode
  text: string
  format?: WriterFormat
  tone?: WriterTone
  length?: WriterLength
  language?: string
  instructions?: string
}

export interface Generation {
  id: string
  request: WriteRequest
  subject: string
  /** Main text first, then alternatives. Editable in place. */
  versions: string[]
  createdAt: number
}

interface WriterOutputProps {
  busy: boolean
  error: string | null
  current: Generation | null
  version: number
  onVersionChange: (index: number) => void
  onEditBody: (value: string) => void
  onEditSubject: (value: string) => void
  onUseAsInput: (body: string) => void
  onRegenerate: () => void
  canRegenerate: boolean
  history: Generation[]
  onSelectHistory: (id: string) => void
}

const describe = (g: Generation) => {
  const format = g.request.format ? FORMATS.find((f) => f.value === g.request.format)?.label : undefined
  return g.request.mode === "translate" ? `Translate → ${g.request.language}` : [modeLabel(g.request.mode), format].filter(Boolean).join(" · ")
}

const timeOf = (ms: number) => new Date(ms).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })

export function WriterOutput({
  busy,
  error,
  current,
  version,
  onVersionChange,
  onEditBody,
  onEditSubject,
  onUseAsInput,
  onRegenerate,
  canRegenerate,
  history,
  onSelectHistory,
}: WriterOutputProps) {
  const router = useRouter()
  const body = current?.versions[version] ?? ""
  const subject = current?.subject ?? ""
  const showSubject = Boolean(current && (subject || current.request.format === "email"))
  const full = subject.trim() ? `Subject: ${subject.trim()}\n\n${body}` : body

  const save = () => {
    if (!current || !body.trim()) return
    const title = subject.trim() || `${describe(current)}: ${body.trim().split("\n")[0].slice(0, 40)}`
    saveNote(full, "manual", title.slice(0, 120))
    toast.success("Saved to notes", { action: { label: "Open notes", onClick: () => router.push("/tools/notes") } })
  }

  const openEmail = () => {
    let b = body
    if (b.length > MAILTO_BODY_LIMIT) {
      b = `${b.slice(0, MAILTO_BODY_LIMIT)}…`
      toast.info("The email body was shortened for your mail app — use Copy for the full text.")
    }
    window.location.href = `mailto:?subject=${encodeURIComponent(subject.trim().slice(0, 200))}&body=${encodeURIComponent(b)}`
  }

  return (
    <section aria-label="Generated text" className="space-y-4">
      <div aria-live="polite" className="sr-only">
        {busy ? "Writing with Gemini…" : current ? `${describe(current)} ready.` : ""}
      </div>

      {busy ? (
        <div aria-busy="true" className="space-y-3 rounded-2xl border bg-card p-4 shadow-soft">
          <Skeleton className="h-10 w-2/3" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-11/12" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-4/5" />
          <Skeleton className="h-4 w-3/5" />
          <p className="pt-1 text-sm text-muted-foreground">Asking Gemini…</p>
        </div>
      ) : error ? (
        <Notice tone="danger" title="Couldn't generate">
          {error}
        </Notice>
      ) : null}

      {!busy && current ? (
        <div className="space-y-4 rounded-2xl border bg-card p-4 shadow-soft">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="text-sm font-medium">{describe(current)}</p>
            <p className="text-xs text-muted-foreground">Generated by Google Gemini · review before using</p>
          </div>

          {current.versions.length > 1 ? (
            <Tabs value={String(version)} onValueChange={(v) => onVersionChange(Number(v))}>
              <TabsList aria-label="Versions" className="w-full sm:w-auto">
                {current.versions.map((_, i) => (
                  <TabsTrigger key={i} value={String(i)} className="px-3">
                    {i === 0 ? "Main" : `Alternative ${i}`}
                  </TabsTrigger>
                ))}
              </TabsList>
            </Tabs>
          ) : null}

          {showSubject ? (
            <div className="space-y-2">
              <Label htmlFor="writer-subject">Subject</Label>
              <Input id="writer-subject" value={subject} maxLength={200} onChange={(e) => onEditSubject(e.target.value)} className="h-10 text-base sm:text-sm" />
            </div>
          ) : null}

          <div className="space-y-2">
            <Label htmlFor="writer-output">{current.request.mode === "translate" ? "Translation" : "Text"} (editable)</Label>
            <Textarea
              id="writer-output"
              value={body}
              onChange={(e) => onEditBody(e.target.value)}
              dir="auto"
              className="min-h-64 resize-y bg-surface text-base leading-relaxed sm:text-sm"
            />
            <p className="text-right text-xs text-muted-foreground tabular-nums">
              {body.trim() ? body.trim().split(/\s+/).length.toLocaleString() : 0} words
            </p>
          </div>

          <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">
            <CopyButton value={full} label={subject.trim() ? "Copy all" : "Copy"} />
            <Button variant="outline" disabled={!body.trim()} onClick={() => onUseAsInput(body)}>
              <ArrowUpLeft aria-hidden /> Use as input
            </Button>
            <Button variant="outline" disabled={!canRegenerate} onClick={onRegenerate}>
              <RefreshCw aria-hidden /> Regenerate
            </Button>
            <Button variant="outline" disabled={!body.trim()} onClick={save}>
              <NotebookPen aria-hidden /> Save to notes
            </Button>
            <Button variant="outline" disabled={!body.trim()} onClick={openEmail} className="col-span-2 sm:col-span-1">
              <Mail aria-hidden /> Open in email
            </Button>
          </div>
        </div>
      ) : null}

      {!busy && !current && !error ? (
        <EmptyState
          icon={PenLine}
          title="Your writing appears here"
          description="Pick a mode, add your text or notes, choose a tone and tap Generate. You can edit, copy, save or email the result."
        />
      ) : null}

      {history.length > 1 ? (
        <div className="space-y-2">
          <p className="flex items-center gap-1.5 text-sm font-medium">
            <History className="size-4 text-muted-foreground" aria-hidden /> Recent (this session)
          </p>
          <ul className="space-y-2">
            {history.map((g) => {
              const active = g.id === current?.id
              return (
                <li key={g.id}>
                  <button
                    type="button"
                    aria-pressed={active}
                    disabled={busy}
                    onClick={() => onSelectHistory(g.id)}
                    className={cn(
                      "flex min-h-12 w-full flex-col items-start gap-0.5 rounded-xl border px-3 py-2 text-left transition-colors outline-none focus-visible:ring-3 focus-visible:ring-ring/50 disabled:opacity-50",
                      active ? "border-primary bg-primary/5" : "bg-card hover:bg-surface-muted"
                    )}
                  >
                    <span className="flex w-full justify-between gap-2 text-xs text-muted-foreground">
                      <span>{describe(g)}</span>
                      <span>{timeOf(g.createdAt)}</span>
                    </span>
                    <span className="line-clamp-1 text-sm">{g.subject || g.versions[0]}</span>
                  </button>
                </li>
              )
            })}
          </ul>
          <p className="text-xs text-muted-foreground">Kept only until you leave this page.</p>
        </div>
      ) : null}
    </section>
  )
}
