"use client"

import { useRef, useState } from "react"
import { LoaderCircle, Replace, Sparkles } from "lucide-react"
import { toast } from "sonner"
import { CopyButton } from "@/components/common/copy-button"
import { Notice } from "@/components/common/notice"
import { ResponsiveSheet } from "@/components/common/responsive-sheet"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useAiStatus } from "@/hooks/use-ai-status"
import { AI_LIMITS, AI_TEXT_ACTIONS, type AiTextActionId } from "@/lib/ai/actions"
import { runAiTextAction } from "@/lib/ai/client"
import { saveNote } from "@/lib/storage/notes"

interface AiTextActionsProps {
  text: string
  /** When provided, the result sheet offers "Replace text". */
  onReplace?: (text: string) => void
  /** Offer "Save as note" in the result sheet. */
  allowSaveNote?: boolean
  size?: "default" | "sm"
  className?: string
}

/**
 * "AI assist" menu (summarize, fix grammar, …) powered by Google Gemini via
 * this app's server. Renders nothing unless a Gemini API key is configured.
 */
export function AiTextActions({ text, onReplace, allowSaveNote = true, size = "default", className }: AiTextActionsProps) {
  const status = useAiStatus()
  const [open, setOpen] = useState(false)
  const [busy, setBusy] = useState<AiTextActionId | null>(null)
  const [result, setResult] = useState<{ action: AiTextActionId; text: string } | null>(null)
  const [error, setError] = useState<string | null>(null)
  const controller = useRef<AbortController | null>(null)

  if (!status?.configured) return null

  const trimmed = text.trim()
  const tooLong = trimmed.length > AI_LIMITS.text
  const label = (id: AiTextActionId) => AI_TEXT_ACTIONS.find((a) => a.id === id)!.label

  const run = async (action: AiTextActionId) => {
    controller.current?.abort()
    const ctl = new AbortController()
    controller.current = ctl
    setBusy(action)
    setError(null)
    setResult(null)
    setOpen(true)
    try {
      const out = await runAiTextAction(action, trimmed, ctl.signal)
      if (!ctl.signal.aborted) setResult({ action, text: out })
    } catch (err) {
      if (!ctl.signal.aborted) setError(err instanceof Error ? err.message : "The AI request failed.")
    } finally {
      if (!ctl.signal.aborted) setBusy(null)
    }
  }

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger
          render={<Button variant="outline" size={size} className={className} disabled={!trimmed || tooLong || busy !== null} />}
        >
          {busy ? <LoaderCircle className="animate-spin" aria-hidden /> : <Sparkles aria-hidden />}
          AI assist
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-64">
          <DropdownMenuGroup>
            <DropdownMenuLabel>Google Gemini</DropdownMenuLabel>
            {AI_TEXT_ACTIONS.map((a) => (
              <DropdownMenuItem key={a.id} onClick={() => void run(a.id)} className="flex-col items-start gap-0">
                <span className="font-medium">{a.label}</span>
                <span className="text-xs text-muted-foreground">{a.description}</span>
              </DropdownMenuItem>
            ))}
          </DropdownMenuGroup>
          <DropdownMenuSeparator />
          <p className="px-2 py-1.5 text-xs text-muted-foreground">Text is sent to Google&apos;s Gemini API.</p>
        </DropdownMenuContent>
      </DropdownMenu>
      {tooLong && (
        <span className="sr-only" role="status">
          Text is too long for AI assist (max {AI_LIMITS.text.toLocaleString()} characters).
        </span>
      )}

      <ResponsiveSheet
        open={open}
        onOpenChange={(o) => {
          if (!o) {
            controller.current?.abort()
            setBusy(null)
          }
          setOpen(o)
        }}
        title={busy ? `${label(busy)}…` : result ? label(result.action) : "AI assist"}
        description="Generated by Google Gemini. Review before using — AI can make mistakes."
        size="lg"
        footer={
          result ? (
            <>
              <CopyButton value={result.text} />
              {allowSaveNote && (
                <Button
                  variant="outline"
                  onClick={() => {
                    saveNote(result.text, "manual", `${label(result.action)}: ${trimmed.split("\n")[0].slice(0, 40)}`)
                    toast.success("Saved to notes")
                  }}
                >
                  Save as note
                </Button>
              )}
              {onReplace && (
                <Button
                  onClick={() => {
                    onReplace(result.text)
                    setOpen(false)
                    toast.success("Text replaced")
                  }}
                >
                  <Replace aria-hidden /> Replace text
                </Button>
              )}
            </>
          ) : null
        }
      >
        <div aria-live="polite">
          {busy && (
            <div className="flex items-center gap-3 rounded-xl bg-surface-muted p-4 text-sm text-muted-foreground">
              <LoaderCircle className="size-4 animate-spin" aria-hidden /> Asking Gemini…
            </div>
          )}
          {error && <Notice tone="danger" title="AI assist failed">{error}</Notice>}
          {result && (
            <div className="max-h-[50dvh] overflow-y-auto rounded-xl border bg-surface-muted p-4 text-sm leading-relaxed whitespace-pre-wrap">
              {result.text}
            </div>
          )}
        </div>
      </ResponsiveSheet>
    </>
  )
}
